spring:
  config:
    import:
    - application-oauth.yml
    - application-static.yml
    - application-aws.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/static/**
  datasource:
    driver-class-name:

